### ISSUE TITLE
Remove redundant `React` imports

### ISSUE THREAD

**Issue by yura2100** [dest-nft/dest.sh#106]
Explicit `import React from "react"` is redundant.

**Comment by 2div** [comment]
Hi , i would like to do this task.
Can you assigned to me?

**Comment by yura2100** [comment]
> Hi , i would like to do this task. Can you assigned to me?

Sure, please use [Gitmoji](https://gitmoji.dev/) convention for commit messages and have fun 😄

**Comment by 2div** [comment]
Hi @yura2100  Kindly check my PR.
Thank you
